# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(934, 624)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 901, 631))
        self.tabWidget.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(86, 164, 158, 255), stop:1 rgba(255, 255, 255, 255));")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.label_3 = QtWidgets.QLabel(self.tab_5)
        self.label_3.setGeometry(QtCore.QRect(20, 50, 151, 16))
        self.label_3.setObjectName("label_3")
        self.verigoster = QtWidgets.QTableWidget(self.tab_5)
        self.verigoster.setGeometry(QtCore.QRect(10, 70, 841, 401))
        self.verigoster.setStyleSheet("background-color: rgb(186, 186, 186);")
        self.verigoster.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.verigoster.setObjectName("verigoster")
        self.verigoster.setColumnCount(0)
        self.verigoster.setRowCount(0)
        self.btnyukle = QtWidgets.QPushButton(self.tab_5)
        self.btnyukle.setGeometry(QtCore.QRect(20, 10, 181, 31))
        self.btnyukle.setStyleSheet("")
        self.btnyukle.setObjectName("btnyukle")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.btnpcauygula = QtWidgets.QPushButton(self.tab_6)
        self.btnpcauygula.setGeometry(QtCore.QRect(20, 20, 171, 31))
        self.btnpcauygula.setStyleSheet("")
        self.btnpcauygula.setObjectName("btnpcauygula")
        self.verigoster2 = QtWidgets.QTableWidget(self.tab_6)
        self.verigoster2.setGeometry(QtCore.QRect(20, 60, 841, 401))
        self.verigoster2.setStyleSheet("background-color: rgb(186, 186, 186);")
        self.verigoster2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.verigoster2.setObjectName("verigoster2")
        self.verigoster2.setColumnCount(0)
        self.verigoster2.setRowCount(0)
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.btnkfold = QtWidgets.QPushButton(self.tab_7)
        self.btnkfold.setGeometry(QtCore.QRect(10, 10, 231, 31))
        self.btnkfold.setStyleSheet("")
        self.btnkfold.setObjectName("btnkfold")
        self.tabWidget.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.btnuygula = QtWidgets.QPushButton(self.tab_8)
        self.btnuygula.setGeometry(QtCore.QRect(10, 10, 111, 31))
        self.btnuygula.setStyleSheet("")
        self.btnuygula.setObjectName("btnuygula")
        self.label_32 = QtWidgets.QLabel(self.tab_8)
        self.label_32.setGeometry(QtCore.QRect(10, 70, 151, 16))
        self.label_32.setStyleSheet("color:red;")
        self.label_32.setObjectName("label_32")
        self.tabWidget.addTab(self.tab_8, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.list_x_train = QtWidgets.QTableWidget(self.tab)
        self.list_x_train.setGeometry(QtCore.QRect(20, 40, 471, 111))
        self.list_x_train.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.list_x_train.setObjectName("list_x_train")
        self.list_x_train.setColumnCount(0)
        self.list_x_train.setRowCount(0)
        self.label_14 = QtWidgets.QLabel(self.tab)
        self.label_14.setGeometry(QtCore.QRect(20, 20, 47, 13))
        self.label_14.setObjectName("label_14")
        self.list_x_test = QtWidgets.QTableWidget(self.tab)
        self.list_x_test.setGeometry(QtCore.QRect(20, 180, 471, 161))
        self.list_x_test.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.list_x_test.setObjectName("list_x_test")
        self.list_x_test.setColumnCount(0)
        self.list_x_test.setRowCount(0)
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setGeometry(QtCore.QRect(20, 160, 47, 13))
        self.label_11.setObjectName("label_11")
        self.list_y_train = QtWidgets.QTableWidget(self.tab)
        self.list_y_train.setGeometry(QtCore.QRect(520, 40, 241, 111))
        self.list_y_train.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.list_y_train.setObjectName("list_y_train")
        self.list_y_train.setColumnCount(0)
        self.list_y_train.setRowCount(0)
        self.label_27 = QtWidgets.QLabel(self.tab)
        self.label_27.setGeometry(QtCore.QRect(520, 10, 47, 13))
        self.label_27.setObjectName("label_27")
        self.label_24 = QtWidgets.QLabel(self.tab)
        self.label_24.setGeometry(QtCore.QRect(520, 160, 47, 13))
        self.label_24.setObjectName("label_24")
        self.list_y_test = QtWidgets.QTableWidget(self.tab)
        self.list_y_test.setGeometry(QtCore.QRect(520, 180, 241, 161))
        self.list_y_test.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.list_y_test.setObjectName("list_y_test")
        self.list_y_test.setColumnCount(0)
        self.list_y_test.setRowCount(0)
        self.lblsonuc2 = QtWidgets.QLabel(self.tab)
        self.lblsonuc2.setGeometry(QtCore.QRect(30, 370, 151, 16))
        self.lblsonuc2.setObjectName("lblsonuc2")
        self.lblsonuc2_2 = QtWidgets.QLabel(self.tab)
        self.lblsonuc2_2.setGeometry(QtCore.QRect(30, 400, 151, 16))
        self.lblsonuc2_2.setObjectName("lblsonuc2_2")
        self.lblsonuc3 = QtWidgets.QLabel(self.tab)
        self.lblsonuc3.setGeometry(QtCore.QRect(30, 430, 151, 16))
        self.lblsonuc3.setObjectName("lblsonuc3")
        self.lblsonuc4 = QtWidgets.QLabel(self.tab)
        self.lblsonuc4.setGeometry(QtCore.QRect(30, 460, 151, 16))
        self.lblsonuc4.setObjectName("lblsonuc4")
        self.lblsonuc5 = QtWidgets.QLabel(self.tab)
        self.lblsonuc5.setGeometry(QtCore.QRect(30, 490, 151, 16))
        self.lblsonuc5.setObjectName("lblsonuc5")
        self.sonuc1 = QtWidgets.QLabel(self.tab)
        self.sonuc1.setGeometry(QtCore.QRect(190, 370, 161, 16))
        self.sonuc1.setText("")
        self.sonuc1.setObjectName("sonuc1")
        self.sonuc2 = QtWidgets.QLabel(self.tab)
        self.sonuc2.setGeometry(QtCore.QRect(190, 400, 161, 16))
        self.sonuc2.setText("")
        self.sonuc2.setObjectName("sonuc2")
        self.sonuc3 = QtWidgets.QLabel(self.tab)
        self.sonuc3.setGeometry(QtCore.QRect(190, 430, 161, 16))
        self.sonuc3.setText("")
        self.sonuc3.setObjectName("sonuc3")
        self.sonuc4 = QtWidgets.QLabel(self.tab)
        self.sonuc4.setGeometry(QtCore.QRect(190, 460, 161, 16))
        self.sonuc4.setText("")
        self.sonuc4.setObjectName("sonuc4")
        self.sonuc5 = QtWidgets.QLabel(self.tab)
        self.sonuc5.setGeometry(QtCore.QRect(190, 490, 161, 16))
        self.sonuc5.setText("")
        self.sonuc5.setObjectName("sonuc5")
        self.lblsonuc3_6 = QtWidgets.QLabel(self.tab)
        self.lblsonuc3_6.setGeometry(QtCore.QRect(390, 430, 151, 16))
        self.lblsonuc3_6.setObjectName("lblsonuc3_6")
        self.sonucort = QtWidgets.QLabel(self.tab)
        self.sonucort.setGeometry(QtCore.QRect(550, 430, 161, 16))
        self.sonucort.setText("")
        self.sonucort.setObjectName("sonucort")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.list_y_train_2 = QtWidgets.QTableWidget(self.tab_2)
        self.list_y_train_2.setGeometry(QtCore.QRect(510, 30, 241, 111))
        self.list_y_train_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.list_y_train_2.setObjectName("list_y_train_2")
        self.list_y_train_2.setColumnCount(0)
        self.list_y_train_2.setRowCount(0)
        self.label_15 = QtWidgets.QLabel(self.tab_2)
        self.label_15.setGeometry(QtCore.QRect(20, 10, 47, 13))
        self.label_15.setObjectName("label_15")
        self.list_y_test_2 = QtWidgets.QTableWidget(self.tab_2)
        self.list_y_test_2.setGeometry(QtCore.QRect(510, 180, 241, 161))
        self.list_y_test_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.list_y_test_2.setObjectName("list_y_test_2")
        self.list_y_test_2.setColumnCount(0)
        self.list_y_test_2.setRowCount(0)
        self.list_x_train_2 = QtWidgets.QTableWidget(self.tab_2)
        self.list_x_train_2.setGeometry(QtCore.QRect(20, 30, 471, 111))
        self.list_x_train_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.list_x_train_2.setObjectName("list_x_train_2")
        self.list_x_train_2.setColumnCount(0)
        self.list_x_train_2.setRowCount(0)
        self.label_25 = QtWidgets.QLabel(self.tab_2)
        self.label_25.setGeometry(QtCore.QRect(510, 150, 47, 13))
        self.label_25.setObjectName("label_25")
        self.label_28 = QtWidgets.QLabel(self.tab_2)
        self.label_28.setGeometry(QtCore.QRect(520, 10, 47, 13))
        self.label_28.setObjectName("label_28")
        self.list_x_test_2 = QtWidgets.QTableWidget(self.tab_2)
        self.list_x_test_2.setGeometry(QtCore.QRect(20, 180, 471, 161))
        self.list_x_test_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.list_x_test_2.setObjectName("list_x_test_2")
        self.list_x_test_2.setColumnCount(0)
        self.list_x_test_2.setRowCount(0)
        self.lblsonuc5_2 = QtWidgets.QLabel(self.tab_2)
        self.lblsonuc5_2.setGeometry(QtCore.QRect(30, 490, 151, 16))
        self.lblsonuc5_2.setObjectName("lblsonuc5_2")
        self.sonuc2_2 = QtWidgets.QLabel(self.tab_2)
        self.sonuc2_2.setGeometry(QtCore.QRect(190, 400, 161, 16))
        self.sonuc2_2.setText("")
        self.sonuc2_2.setObjectName("sonuc2_2")
        self.lblsonuc4_2 = QtWidgets.QLabel(self.tab_2)
        self.lblsonuc4_2.setGeometry(QtCore.QRect(30, 460, 151, 16))
        self.lblsonuc4_2.setObjectName("lblsonuc4_2")
        self.lblsonuc2_3 = QtWidgets.QLabel(self.tab_2)
        self.lblsonuc2_3.setGeometry(QtCore.QRect(30, 400, 151, 16))
        self.lblsonuc2_3.setObjectName("lblsonuc2_3")
        self.lblsonuc2_4 = QtWidgets.QLabel(self.tab_2)
        self.lblsonuc2_4.setGeometry(QtCore.QRect(30, 370, 151, 16))
        self.lblsonuc2_4.setObjectName("lblsonuc2_4")
        self.lblsonuc3_2 = QtWidgets.QLabel(self.tab_2)
        self.lblsonuc3_2.setGeometry(QtCore.QRect(30, 430, 151, 16))
        self.lblsonuc3_2.setObjectName("lblsonuc3_2")
        self.sonuc3_2 = QtWidgets.QLabel(self.tab_2)
        self.sonuc3_2.setGeometry(QtCore.QRect(190, 430, 161, 16))
        self.sonuc3_2.setText("")
        self.sonuc3_2.setObjectName("sonuc3_2")
        self.sonuc4_2 = QtWidgets.QLabel(self.tab_2)
        self.sonuc4_2.setGeometry(QtCore.QRect(190, 460, 161, 16))
        self.sonuc4_2.setText("")
        self.sonuc4_2.setObjectName("sonuc4_2")
        self.sonuc1_2 = QtWidgets.QLabel(self.tab_2)
        self.sonuc1_2.setGeometry(QtCore.QRect(190, 370, 161, 16))
        self.sonuc1_2.setText("")
        self.sonuc1_2.setObjectName("sonuc1_2")
        self.sonuc5_2 = QtWidgets.QLabel(self.tab_2)
        self.sonuc5_2.setGeometry(QtCore.QRect(190, 490, 161, 16))
        self.sonuc5_2.setText("")
        self.sonuc5_2.setObjectName("sonuc5_2")
        self.sonucort_2 = QtWidgets.QLabel(self.tab_2)
        self.sonucort_2.setGeometry(QtCore.QRect(560, 430, 161, 16))
        self.sonucort_2.setText("")
        self.sonucort_2.setObjectName("sonucort_2")
        self.lblsonuc3_7 = QtWidgets.QLabel(self.tab_2)
        self.lblsonuc3_7.setGeometry(QtCore.QRect(400, 430, 151, 16))
        self.lblsonuc3_7.setObjectName("lblsonuc3_7")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.list_y_train_3 = QtWidgets.QTableWidget(self.tab_3)
        self.list_y_train_3.setGeometry(QtCore.QRect(520, 60, 241, 111))
        self.list_y_train_3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.list_y_train_3.setObjectName("list_y_train_3")
        self.list_y_train_3.setColumnCount(0)
        self.list_y_train_3.setRowCount(0)
        self.label_16 = QtWidgets.QLabel(self.tab_3)
        self.label_16.setGeometry(QtCore.QRect(20, 40, 47, 13))
        self.label_16.setObjectName("label_16")
        self.list_y_test_3 = QtWidgets.QTableWidget(self.tab_3)
        self.list_y_test_3.setGeometry(QtCore.QRect(520, 200, 241, 161))
        self.list_y_test_3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.list_y_test_3.setObjectName("list_y_test_3")
        self.list_y_test_3.setColumnCount(0)
        self.list_y_test_3.setRowCount(0)
        self.list_x_train_3 = QtWidgets.QTableWidget(self.tab_3)
        self.list_x_train_3.setGeometry(QtCore.QRect(20, 60, 471, 111))
        self.list_x_train_3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.list_x_train_3.setObjectName("list_x_train_3")
        self.list_x_train_3.setColumnCount(0)
        self.list_x_train_3.setRowCount(0)
        self.label_26 = QtWidgets.QLabel(self.tab_3)
        self.label_26.setGeometry(QtCore.QRect(520, 180, 47, 13))
        self.label_26.setObjectName("label_26")
        self.label_29 = QtWidgets.QLabel(self.tab_3)
        self.label_29.setGeometry(QtCore.QRect(520, 40, 47, 13))
        self.label_29.setObjectName("label_29")
        self.list_x_test_3 = QtWidgets.QTableWidget(self.tab_3)
        self.list_x_test_3.setGeometry(QtCore.QRect(20, 200, 471, 161))
        self.list_x_test_3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.list_x_test_3.setObjectName("list_x_test_3")
        self.list_x_test_3.setColumnCount(0)
        self.list_x_test_3.setRowCount(0)
        self.lblsonuc5_3 = QtWidgets.QLabel(self.tab_3)
        self.lblsonuc5_3.setGeometry(QtCore.QRect(20, 500, 151, 16))
        self.lblsonuc5_3.setObjectName("lblsonuc5_3")
        self.sonuc2_3 = QtWidgets.QLabel(self.tab_3)
        self.sonuc2_3.setGeometry(QtCore.QRect(180, 410, 161, 16))
        self.sonuc2_3.setText("")
        self.sonuc2_3.setObjectName("sonuc2_3")
        self.lblsonuc4_3 = QtWidgets.QLabel(self.tab_3)
        self.lblsonuc4_3.setGeometry(QtCore.QRect(20, 470, 151, 16))
        self.lblsonuc4_3.setObjectName("lblsonuc4_3")
        self.lblsonuc2_5 = QtWidgets.QLabel(self.tab_3)
        self.lblsonuc2_5.setGeometry(QtCore.QRect(20, 410, 151, 16))
        self.lblsonuc2_5.setObjectName("lblsonuc2_5")
        self.lblsonuc2_6 = QtWidgets.QLabel(self.tab_3)
        self.lblsonuc2_6.setGeometry(QtCore.QRect(20, 380, 151, 16))
        self.lblsonuc2_6.setObjectName("lblsonuc2_6")
        self.lblsonuc3_3 = QtWidgets.QLabel(self.tab_3)
        self.lblsonuc3_3.setGeometry(QtCore.QRect(20, 440, 151, 16))
        self.lblsonuc3_3.setObjectName("lblsonuc3_3")
        self.sonuc3_3 = QtWidgets.QLabel(self.tab_3)
        self.sonuc3_3.setGeometry(QtCore.QRect(180, 440, 161, 16))
        self.sonuc3_3.setText("")
        self.sonuc3_3.setObjectName("sonuc3_3")
        self.sonuc4_3 = QtWidgets.QLabel(self.tab_3)
        self.sonuc4_3.setGeometry(QtCore.QRect(180, 470, 161, 16))
        self.sonuc4_3.setText("")
        self.sonuc4_3.setObjectName("sonuc4_3")
        self.sonuc1_3 = QtWidgets.QLabel(self.tab_3)
        self.sonuc1_3.setGeometry(QtCore.QRect(180, 380, 161, 16))
        self.sonuc1_3.setText("")
        self.sonuc1_3.setObjectName("sonuc1_3")
        self.sonuc5_3 = QtWidgets.QLabel(self.tab_3)
        self.sonuc5_3.setGeometry(QtCore.QRect(180, 500, 161, 16))
        self.sonuc5_3.setText("")
        self.sonuc5_3.setObjectName("sonuc5_3")
        self.sonucort_3 = QtWidgets.QLabel(self.tab_3)
        self.sonucort_3.setGeometry(QtCore.QRect(570, 440, 161, 16))
        self.sonucort_3.setText("")
        self.sonucort_3.setObjectName("sonucort_3")
        self.lblsonuc3_8 = QtWidgets.QLabel(self.tab_3)
        self.lblsonuc3_8.setGeometry(QtCore.QRect(410, 440, 151, 16))
        self.lblsonuc3_8.setObjectName("lblsonuc3_8")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.list_y_train_4 = QtWidgets.QTableWidget(self.tab_4)
        self.list_y_train_4.setGeometry(QtCore.QRect(520, 50, 241, 111))
        self.list_y_train_4.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.list_y_train_4.setObjectName("list_y_train_4")
        self.list_y_train_4.setColumnCount(0)
        self.list_y_train_4.setRowCount(0)
        self.label_17 = QtWidgets.QLabel(self.tab_4)
        self.label_17.setGeometry(QtCore.QRect(20, 30, 47, 13))
        self.label_17.setObjectName("label_17")
        self.list_y_test_4 = QtWidgets.QTableWidget(self.tab_4)
        self.list_y_test_4.setGeometry(QtCore.QRect(520, 190, 241, 161))
        self.list_y_test_4.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.list_y_test_4.setObjectName("list_y_test_4")
        self.list_y_test_4.setColumnCount(0)
        self.list_y_test_4.setRowCount(0)
        self.list_x_train_4 = QtWidgets.QTableWidget(self.tab_4)
        self.list_x_train_4.setGeometry(QtCore.QRect(20, 50, 471, 111))
        self.list_x_train_4.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.list_x_train_4.setObjectName("list_x_train_4")
        self.list_x_train_4.setColumnCount(0)
        self.list_x_train_4.setRowCount(0)
        self.label_30 = QtWidgets.QLabel(self.tab_4)
        self.label_30.setGeometry(QtCore.QRect(520, 170, 47, 13))
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.tab_4)
        self.label_31.setGeometry(QtCore.QRect(520, 30, 47, 13))
        self.label_31.setObjectName("label_31")
        self.list_x_test_4 = QtWidgets.QTableWidget(self.tab_4)
        self.list_x_test_4.setGeometry(QtCore.QRect(20, 190, 471, 161))
        self.list_x_test_4.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.list_x_test_4.setObjectName("list_x_test_4")
        self.list_x_test_4.setColumnCount(0)
        self.list_x_test_4.setRowCount(0)
        self.lblsonuc5_4 = QtWidgets.QLabel(self.tab_4)
        self.lblsonuc5_4.setGeometry(QtCore.QRect(20, 490, 151, 16))
        self.lblsonuc5_4.setObjectName("lblsonuc5_4")
        self.sonuc2_4 = QtWidgets.QLabel(self.tab_4)
        self.sonuc2_4.setGeometry(QtCore.QRect(180, 400, 161, 16))
        self.sonuc2_4.setText("")
        self.sonuc2_4.setObjectName("sonuc2_4")
        self.lblsonuc4_4 = QtWidgets.QLabel(self.tab_4)
        self.lblsonuc4_4.setGeometry(QtCore.QRect(20, 460, 151, 16))
        self.lblsonuc4_4.setObjectName("lblsonuc4_4")
        self.lblsonuc2_7 = QtWidgets.QLabel(self.tab_4)
        self.lblsonuc2_7.setGeometry(QtCore.QRect(20, 400, 151, 16))
        self.lblsonuc2_7.setObjectName("lblsonuc2_7")
        self.lblsonuc2_8 = QtWidgets.QLabel(self.tab_4)
        self.lblsonuc2_8.setGeometry(QtCore.QRect(20, 370, 151, 16))
        self.lblsonuc2_8.setObjectName("lblsonuc2_8")
        self.lblsonuc3_4 = QtWidgets.QLabel(self.tab_4)
        self.lblsonuc3_4.setGeometry(QtCore.QRect(20, 430, 151, 16))
        self.lblsonuc3_4.setObjectName("lblsonuc3_4")
        self.sonuc3_4 = QtWidgets.QLabel(self.tab_4)
        self.sonuc3_4.setGeometry(QtCore.QRect(180, 430, 161, 16))
        self.sonuc3_4.setText("")
        self.sonuc3_4.setObjectName("sonuc3_4")
        self.sonuc4_4 = QtWidgets.QLabel(self.tab_4)
        self.sonuc4_4.setGeometry(QtCore.QRect(180, 460, 161, 16))
        self.sonuc4_4.setText("")
        self.sonuc4_4.setObjectName("sonuc4_4")
        self.sonuc1_4 = QtWidgets.QLabel(self.tab_4)
        self.sonuc1_4.setGeometry(QtCore.QRect(180, 370, 161, 16))
        self.sonuc1_4.setText("")
        self.sonuc1_4.setObjectName("sonuc1_4")
        self.sonuc5_4 = QtWidgets.QLabel(self.tab_4)
        self.sonuc5_4.setGeometry(QtCore.QRect(180, 490, 161, 16))
        self.sonuc5_4.setText("")
        self.sonuc5_4.setObjectName("sonuc5_4")
        self.sonucort_4 = QtWidgets.QLabel(self.tab_4)
        self.sonucort_4.setGeometry(QtCore.QRect(570, 440, 161, 16))
        self.sonucort_4.setText("")
        self.sonucort_4.setObjectName("sonucort_4")
        self.lblsonuc3_9 = QtWidgets.QLabel(self.tab_4)
        self.lblsonuc3_9.setGeometry(QtCore.QRect(410, 440, 151, 16))
        self.lblsonuc3_9.setObjectName("lblsonuc3_9")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.list_y_train_5 = QtWidgets.QTableWidget(self.tab_9)
        self.list_y_train_5.setGeometry(QtCore.QRect(520, 50, 241, 111))
        self.list_y_train_5.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.list_y_train_5.setObjectName("list_y_train_5")
        self.list_y_train_5.setColumnCount(0)
        self.list_y_train_5.setRowCount(0)
        self.label_18 = QtWidgets.QLabel(self.tab_9)
        self.label_18.setGeometry(QtCore.QRect(20, 30, 47, 13))
        self.label_18.setObjectName("label_18")
        self.list_y_test_5 = QtWidgets.QTableWidget(self.tab_9)
        self.list_y_test_5.setGeometry(QtCore.QRect(520, 190, 241, 161))
        self.list_y_test_5.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.list_y_test_5.setObjectName("list_y_test_5")
        self.list_y_test_5.setColumnCount(0)
        self.list_y_test_5.setRowCount(0)
        self.list_x_train_5 = QtWidgets.QTableWidget(self.tab_9)
        self.list_x_train_5.setGeometry(QtCore.QRect(20, 50, 471, 111))
        self.list_x_train_5.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.list_x_train_5.setObjectName("list_x_train_5")
        self.list_x_train_5.setColumnCount(0)
        self.list_x_train_5.setRowCount(0)
        self.label_33 = QtWidgets.QLabel(self.tab_9)
        self.label_33.setGeometry(QtCore.QRect(520, 170, 47, 13))
        self.label_33.setObjectName("label_33")
        self.label_35 = QtWidgets.QLabel(self.tab_9)
        self.label_35.setGeometry(QtCore.QRect(520, 30, 47, 13))
        self.label_35.setObjectName("label_35")
        self.list_x_test_5 = QtWidgets.QTableWidget(self.tab_9)
        self.list_x_test_5.setGeometry(QtCore.QRect(20, 190, 471, 161))
        self.list_x_test_5.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.list_x_test_5.setObjectName("list_x_test_5")
        self.list_x_test_5.setColumnCount(0)
        self.list_x_test_5.setRowCount(0)
        self.lblsonuc5_5 = QtWidgets.QLabel(self.tab_9)
        self.lblsonuc5_5.setGeometry(QtCore.QRect(20, 490, 151, 16))
        self.lblsonuc5_5.setObjectName("lblsonuc5_5")
        self.sonuc2_5 = QtWidgets.QLabel(self.tab_9)
        self.sonuc2_5.setGeometry(QtCore.QRect(180, 400, 161, 16))
        self.sonuc2_5.setText("")
        self.sonuc2_5.setObjectName("sonuc2_5")
        self.lblsonuc4_5 = QtWidgets.QLabel(self.tab_9)
        self.lblsonuc4_5.setGeometry(QtCore.QRect(20, 460, 151, 16))
        self.lblsonuc4_5.setObjectName("lblsonuc4_5")
        self.lblsonuc2_9 = QtWidgets.QLabel(self.tab_9)
        self.lblsonuc2_9.setGeometry(QtCore.QRect(20, 400, 151, 16))
        self.lblsonuc2_9.setObjectName("lblsonuc2_9")
        self.lblsonuc2_10 = QtWidgets.QLabel(self.tab_9)
        self.lblsonuc2_10.setGeometry(QtCore.QRect(20, 370, 151, 16))
        self.lblsonuc2_10.setObjectName("lblsonuc2_10")
        self.lblsonuc3_5 = QtWidgets.QLabel(self.tab_9)
        self.lblsonuc3_5.setGeometry(QtCore.QRect(20, 430, 151, 16))
        self.lblsonuc3_5.setObjectName("lblsonuc3_5")
        self.sonuc3_5 = QtWidgets.QLabel(self.tab_9)
        self.sonuc3_5.setGeometry(QtCore.QRect(180, 430, 161, 16))
        self.sonuc3_5.setText("")
        self.sonuc3_5.setObjectName("sonuc3_5")
        self.sonuc4_5 = QtWidgets.QLabel(self.tab_9)
        self.sonuc4_5.setGeometry(QtCore.QRect(180, 460, 161, 16))
        self.sonuc4_5.setText("")
        self.sonuc4_5.setObjectName("sonuc4_5")
        self.sonuc1_5 = QtWidgets.QLabel(self.tab_9)
        self.sonuc1_5.setGeometry(QtCore.QRect(180, 370, 161, 16))
        self.sonuc1_5.setText("")
        self.sonuc1_5.setObjectName("sonuc1_5")
        self.sonuc5_5 = QtWidgets.QLabel(self.tab_9)
        self.sonuc5_5.setGeometry(QtCore.QRect(180, 490, 161, 16))
        self.sonuc5_5.setText("")
        self.sonuc5_5.setObjectName("sonuc5_5")
        self.sonucort_5 = QtWidgets.QLabel(self.tab_9)
        self.sonucort_5.setGeometry(QtCore.QRect(570, 420, 161, 16))
        self.sonucort_5.setText("")
        self.sonucort_5.setObjectName("sonucort_5")
        self.lblsonuc3_10 = QtWidgets.QLabel(self.tab_9)
        self.lblsonuc3_10.setGeometry(QtCore.QRect(410, 420, 151, 16))
        self.lblsonuc3_10.setObjectName("lblsonuc3_10")
        self.tabWidget.addTab(self.tab_9, "")
        self.sonuclar = QtWidgets.QTableWidget(self.centralwidget)
        self.sonuclar.setEnabled(False)
        self.sonuclar.setGeometry(QtCore.QRect(20, 270, 741, 171))
        self.sonuclar.setToolTip("")
        self.sonuclar.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.sonuclar.setShowGrid(False)
        self.sonuclar.setWordWrap(False)
        self.sonuclar.setObjectName("sonuclar")
        self.sonuclar.setColumnCount(0)
        self.sonuclar.setRowCount(0)
        self.sonuclar.raise_()
        self.tabWidget.raise_()

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "İNSAN ETKİNLİĞİ VERİSİ :"))
        self.btnyukle.setText(_translate("MainWindow", "VERİLERİ YÜKLE"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "verileri yükle"))
        self.btnpcauygula.setText(_translate("MainWindow", "P C A"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "PCA işlemi uygula"))
        self.btnkfold.setText(_translate("MainWindow", "K F O L D İŞLEMİ UYGULA"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("MainWindow", "K-FOLD AYIRMA İŞLEMİ"))
        self.btnuygula.setText(_translate("MainWindow", "UYGULA"))
        self.label_32.setText(_translate("MainWindow", "AYRINTILAR"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), _translate("MainWindow", "SONUÇ"))
        self.label_14.setText(_translate("MainWindow", "X  T r a i n"))
        self.label_11.setText(_translate("MainWindow", "X  T e s t"))
        self.label_27.setText(_translate("MainWindow", "Y  T r a i n"))
        self.label_24.setText(_translate("MainWindow", "Y  T e s t"))
        self.lblsonuc2.setText(_translate("MainWindow", "1. ALGORİTMA SONUCU :"))
        self.lblsonuc2_2.setText(_translate("MainWindow", "2. ALGORİTMA SONUCU"))
        self.lblsonuc3.setText(_translate("MainWindow", "3. ALGORİTMA SONUCU"))
        self.lblsonuc4.setText(_translate("MainWindow", "4. ALGORİTMA SONUCU"))
        self.lblsonuc5.setText(_translate("MainWindow", "5. ALGORİTMA SONUCU"))
        self.lblsonuc3_6.setText(_translate("MainWindow", "SONUC ORTALAMALARI:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "1. veri seti"))
        self.label_15.setText(_translate("MainWindow", "X  T r a i n"))
        self.label_25.setText(_translate("MainWindow", "Y  T e s t"))
        self.label_28.setText(_translate("MainWindow", "Y  T r a i n"))
        self.lblsonuc5_2.setText(_translate("MainWindow", "5. ALGORİTMA SONUCU"))
        self.lblsonuc4_2.setText(_translate("MainWindow", "4. ALGORİTMA SONUCU"))
        self.lblsonuc2_3.setText(_translate("MainWindow", "2. ALGORİTMA SONUCU"))
        self.lblsonuc2_4.setText(_translate("MainWindow", "1. ALGORİTMA SONUCU :"))
        self.lblsonuc3_2.setText(_translate("MainWindow", "3. ALGORİTMA SONUCU"))
        self.lblsonuc3_7.setText(_translate("MainWindow", "SONUC ORTALAMALARI:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "2. veriseti"))
        self.label_16.setText(_translate("MainWindow", "X  T r a i n"))
        self.label_26.setText(_translate("MainWindow", "Y  T e s t"))
        self.label_29.setText(_translate("MainWindow", "Y  T r a i n"))
        self.lblsonuc5_3.setText(_translate("MainWindow", "5. ALGORİTMA SONUCU"))
        self.lblsonuc4_3.setText(_translate("MainWindow", "4. ALGORİTMA SONUCU"))
        self.lblsonuc2_5.setText(_translate("MainWindow", "2. ALGORİTMA SONUCU"))
        self.lblsonuc2_6.setText(_translate("MainWindow", "1. ALGORİTMA SONUCU :"))
        self.lblsonuc3_3.setText(_translate("MainWindow", "3. ALGORİTMA SONUCU"))
        self.lblsonuc3_8.setText(_translate("MainWindow", "SONUC ORTALAMALARI:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "3. veriseti"))
        self.label_17.setText(_translate("MainWindow", "X  T r a i n"))
        self.label_30.setText(_translate("MainWindow", "Y  T e s t"))
        self.label_31.setText(_translate("MainWindow", "Y  T r a i n"))
        self.lblsonuc5_4.setText(_translate("MainWindow", "5. ALGORİTMA SONUCU"))
        self.lblsonuc4_4.setText(_translate("MainWindow", "4. ALGORİTMA SONUCU"))
        self.lblsonuc2_7.setText(_translate("MainWindow", "2. ALGORİTMA SONUCU"))
        self.lblsonuc2_8.setText(_translate("MainWindow", "1. ALGORİTMA SONUCU :"))
        self.lblsonuc3_4.setText(_translate("MainWindow", "3. ALGORİTMA SONUCU"))
        self.lblsonuc3_9.setText(_translate("MainWindow", "SONUC ORTALAMALARI:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "4. veriseti"))
        self.label_18.setText(_translate("MainWindow", "X  T r a i n"))
        self.label_33.setText(_translate("MainWindow", "Y  T e s t"))
        self.label_35.setText(_translate("MainWindow", "Y  T r a i n"))
        self.lblsonuc5_5.setText(_translate("MainWindow", "5. ALGORİTMA SONUCU"))
        self.lblsonuc4_5.setText(_translate("MainWindow", "4. ALGORİTMA SONUCU"))
        self.lblsonuc2_9.setText(_translate("MainWindow", "2. ALGORİTMA SONUCU"))
        self.lblsonuc2_10.setText(_translate("MainWindow", "1. ALGORİTMA SONUCU :"))
        self.lblsonuc3_5.setText(_translate("MainWindow", "3. ALGORİTMA SONUCU"))
        self.lblsonuc3_10.setText(_translate("MainWindow", "SONUC ORTALAMALARI:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_9), _translate("MainWindow", "5. veriseti"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

